### ISSUE TITLE
support stdin for text input

### ISSUE THREAD

**Issue by nicki-krizek** [CZ-NIC/convey#38]
I'd find it useful if I could pass text input to convey using stdin. For example:

```
$ echo "acddf" | convey -f reg
$ cat file* | convey -f reg
```

I tried using the `-i` option as well, but convey crashes either way.

```bash
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/convey/__main__.py", line 18, in main
    Controller()
  File "/usr/lib/python3.8/site-packages/convey/controller.py", line 249, in __init__
    self.source_new_column(target_type, add, source_field, source_type, custom)
  File "/usr/lib/python3.8/site-packages/convey/controller.py", line 538, in source_new_column
    *custom, target_type = Preview(source_field, source_type, target_type).reg()
  File "/usr/lib/python3.8/site-packages/convey/wizzard.py", line 298, in reg
    self.search = self.reset_session().prompt('Regular match: ', **options, default=self.search,
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/shortcuts/prompt.py", line 797, in prompt
    return run_sync()
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/shortcuts/prompt.py", line 786, in run_sync
    return self.app.run(inputhook=self.inputhook, pre_run=pre_run2)
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 736, in run
    return run()
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 710, in run
    return f.result()
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/eventloop/future.py", line 151, in result
    raise self._exception
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/eventloop/coroutine.py", line 92, in step_next
    new_f = coroutine.throw(exc)
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 685, in _run_async2
    result = yield f
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/eventloop/coroutine.py", line 92, in step_next
    new_f = coroutine.throw(exc)
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 637, in _run_async
    result = yield From(f)
EOFError
```

```json5
{'epilog': 'To launch a web service see README.md.', 'column_help': 'COLUMN is ID the column (1, 2, 3...), the exact column name, field type name or its usual name.', 'parser': ArgumentParser(prog='convey', usage=None, description='Data conversion swiss knife', formatter_class=<class 'convey.controller.SmartFormatter'>, conflict_handler='error', add_help=True), 'csv_flags': [('otrs_id', 'Ticket id'), ('otrs_num', 'Ticket num'), ('otrs_cookie', 'OTRS cookie'), ('otrs_token', 'OTRS token')], 'flag': ('otrs_token', 'OTRS token'), 'args': Namespace(compute_preview=None, config=None, csirt_incident=False, csv_processing=False, debug=False, delete=None, delete_whois_cache=False, delimiter=None, dig=None, disable_external=False, field=None, field_excluded=None, file=False, file_or_input=None, fresh=False, header=False, headless=False, input=False, json=False, multiple_cidr_ip=None, multiple_hostname_ip=None, nmap=None, no_header=False, otrs_cookie=None, otrs_id=None, otrs_num=None, otrs_token=None, output=None, quiet=False, quote_char=None, show_uml=None, single_detect=False, single_query=False, sort=None, split=None, user_agent=None, verbose=False, version=False, web=None, whois=None, whois_ttl=None, yes=False), 'module': 'dig', 'c': [], 'add': True, 'custom': [], 'target_type': Type(reg), 'm': None, 'source_field': <Field Listen=[::1]:53 (Datagram)\nListen=[::1]:53 (Stream)\nListen=127.0.0.1:53 (Datagram)\nListen=127.0.0.1:53 (Stream)\nListen=[::]:53 (Datagram)\nListenStream=192.0.2.1:443\nListenStream=[::beef]:443\nListenStream=[::1]:853\nListenStream=127.0.0.1:853\nListenStream=[::]:888\nListen=[::1]:853 (Stream)\nListen=127.0.0.1:853 (Stream)\nListen=[::]:888 (Stream)\nListenStream=[::1]:8453\nListenStream=127.0.0.1:8453\nListenStream=/unix/path\n(any_ip)>, 'source_type': Type(quoted_printable), 'self': <convey.controller.Controller object at 0x7f31f3e56760>, 'task': ['reg']}
```

**Comment by ghost** [comment]
I recommend looking at [argparse's FileType](https://docs.python.org/3/library/argparse.html#filetype-objects)

**Comment by e3rd** [comment]
Very interesting usecase I did not think of. The problem is convey tries to open the wizzard that needs user input from STDIN. But STDIN is not available any more – the process STDIN was the pipe, not the terminal input.

The solution is to try the wizzard without piping to process because if we specify all the `reg` type attributes and no wizzard is needed, everything is alright:
```bash
echo "acddf" | convey -f reg # failed because STDIN is gone for wizzard
echo "acddf" | convey -f reg_s,"d","D" # prints out acDDf
```
I fear this is not an easy issue to resolve, I have to think of it a lot. Maybe the solution will be the convey just prints out it is not possible to open the wizzard because STDIN is gone.

I did not know about argparse FileType, interesting! However I think this will be of no help because piping to FileType does not mean a terminal STDIN will stay open.

**Comment by nicki-krizek** [comment]
It's seems much more complicated than I first thought. There's probably no good solution for _both_ having STDIN as the input and still using the interactive mode.

I'm okay with the workarounds that are available - either redirecting to a file and then using it for convey, or specifying all the arguments explicitly

**Comment by e3rd** [comment]
I've found a way, it should work now!  
However, since POSIX pipe that I can gain has much less features than the pseudo-terminal one, the wizzard is reduced (no colors, etc.)

https://github.com/prompt-toolkit/python-prompt-toolkit/issues/502
