### ISSUE TITLE
impossible to exit interactive mode for reg

### ISSUE THREAD

**Issue by nicki-krizek** [CZ-NIC/convey#39]
I'm not able to cleanly exit the interactive mode for `-f reg` using typical `KeyboardInterrupt` (with `C-c`), nor can I close the application with `C-d`.

Holding down `C-c` instead of hitting it sometimes work, but otherwise I get the errors below.

From what I saw in the code, it seems the issue is `prompt_toolkit.PromptSession` consumes these keypresses and it doesn't raise any exception.

```bash
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/convey/__main__.py", line 18, in main
    Controller()
  File "/usr/lib/python3.8/site-packages/convey/controller.py", line 249, in __init__
    self.source_new_column(target_type, add, source_field, source_type, custom)
  File "/usr/lib/python3.8/site-packages/convey/controller.py", line 568, in source_new_column
    path = graph.dijkstra(target_type, start=source_type, ignore_private=True)
  File "/usr/lib/python3.8/site-packages/convey/graph.py", line 37, in dijkstra
    visited = {target: 0}
TypeError: unhashable type: 'list'
```

```json5
{'epilog': 'To launch a web service see README.md.', 'column_help': 'COLUMN is ID the column (1, 2, 3...), the exact column name, field type name or its usual name.', 'parser': ArgumentParser(prog='convey', usage=None, description='Data conversion swiss knife', formatter_class=<class 'convey.controller.SmartFormatter'>, conflict_handler='error', add_help=True), 'csv_flags': [('otrs_id', 'Ticket id'), ('otrs_num', 'Ticket num'), ('otrs_cookie', 'OTRS cookie'), ('otrs_token', 'OTRS token')], 'flag': ('otrs_token', 'OTRS token'), 'args': Namespace(compute_preview=None, config=None, csirt_incident=False, csv_processing=False, debug=False, delete=None, delete_whois_cache=False, delimiter=None, dig=None, disable_external=False, field=None, field_excluded=None, file=False, file_or_input='all', fresh=False, header=False, headless=False, input=False, json=False, multiple_cidr_ip=None, multiple_hostname_ip=None, nmap=None, no_header=False, otrs_cookie=None, otrs_id=None, otrs_num=None, otrs_token=None, output=None, quiet=False, quote_char=None, show_uml=None, single_detect=False, single_query=False, sort=None, split=None, user_agent=None, verbose=False, version=False, web=None, whois=None, whois_ttl=None, yes=False), 'module': 'dig', 'c': [], 'add': True, 'custom': [], 'target_type': Type(reg), 'm': None, 'source_field': <Field Listen=[::1]:53 (Datagram)(None)>, 'source_type': Type(plaintext), 'self': <convey.controller.Controller object at 0x7f48e9b97760>, 'task': ['reg']}
```

**Comment by e3rd** [comment]
Try now, please, C-c should work!
